# Generated by Django 4.1.1 on 2022-09-14 01:56

import computedfields.resolver
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("fte_14_day", models.FloatField()),
                ("streak_pref", models.IntegerField(default=3)),
                ("fte", models.IntegerField(editable=False)),
            ],
            options={
                "abstract": False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start", models.TimeField()),
                ("duration", models.DurationField()),
                (
                    "occur_days",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            (0, "Sunday"),
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                        ],
                        default=[0, 1, 2, 3, 4, 5, 6],
                        max_length=14,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("slug", models.SlugField(editable=False, max_length=20)),
                ("iweekday", models.IntegerField(editable=False)),
                ("iweek", models.IntegerField(editable=False)),
                ("iperiod", models.IntegerField(editable=False)),
                ("shifts", models.ManyToManyField(editable=False, to="sch.shift")),
            ],
            options={
                "abstract": False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=20)),
                ("start", models.DateTimeField(editable=False)),
                ("end", models.DateTimeField(editable=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sch.employee"
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sch.shift"
                    ),
                ),
                (
                    "workday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sch.workday"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.AddField(
            model_name="employee",
            name="shifts_available",
            field=models.ManyToManyField(related_name="available", to="sch.shift"),
        ),
        migrations.AddField(
            model_name="employee",
            name="shifts_trained",
            field=models.ManyToManyField(related_name="trained", to="sch.shift"),
        ),
        migrations.CreateModel(
            name="ShiftTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ppd_id", models.IntegerField()),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sch.employee",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sch.shift"
                    ),
                ),
            ],
            options={
                "unique_together": {("shift", "ppd_id")},
            },
        ),
    ]
