# Generated by Django 4.1.1 on 2022-11-05 18:20

import computedfields.resolver
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fte_14_day', models.FloatField()),
                ('streak_pref', models.IntegerField(default=3)),
                ('cls', models.CharField(blank=True, choices=[('CPhT', 'CPhT'), ('RPh', 'RPh')], default='CPhT', max_length=4, null=True)),
                ('evening_pref', models.BooleanField(default=False)),
                ('fte', models.FloatField(editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.CreateModel(
            name='EmployeeClass',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cls', models.CharField(choices=[('CPhT', 'CPhT'), ('RPh', 'RPh')], max_length=5, null=True)),
                ('start', models.TimeField()),
                ('hours', models.FloatField(default=0)),
                ('duration', models.DurationField(default=0)),
                ('occur_days', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=[0, 1, 2, 3, 4, 5, 6], max_length=14)),
                ('is_iv', models.BooleanField(default=False)),
                ('group', models.CharField(default='', max_length=3, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iweek', models.IntegerField()),
                ('year', models.IntegerField()),
                ('workdays', models.IntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.CreateModel(
            name='Workday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scheduleId', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('iweekday', models.IntegerField(default=0)),
                ('iweek', models.IntegerField(default=0)),
                ('iperiod', models.IntegerField(default=0)),
                ('ischedule', models.IntegerField(default=0)),
                ('ppd_id', models.IntegerField(default=0)),
                ('sd_id', models.IntegerField(default=0)),
                ('periodId', models.IntegerField(null=True)),
                ('slug', models.SlugField(editable=False, max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.CreateModel(
            name='SwapMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=5000)),
                ('workday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sch.workday')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=20)),
                ('hours', models.FloatField(editable=False)),
                ('is_turnaround', models.IntegerField(editable=False)),
                ('is_preturnaround', models.IntegerField(editable=False)),
                ('is_terminal', models.BooleanField(editable=False)),
                ('streak', models.IntegerField(editable=False)),
                ('isOverStreakPref', models.BooleanField(editable=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sch.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sch.shift')),
                ('workday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sch.workday')),
            ],
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppd_id', models.IntegerField()),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sch.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sch.shift')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('SP', 'Strongly Prefer'), ('P', 'Prefer'), ('N', 'Neutral'), ('D', 'Dislike'), ('SD', 'Strongly Dislike')], default='N', max_length=2)),
                ('score', models.IntegerField(editable=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sch.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sch.shift')),
            ],
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.CreateModel(
            name='SchedulingMax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('pay_period', models.IntegerField(blank=True, null=True)),
                ('max_hours', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sch.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PtoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workday', models.DateField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Denied')], default='P', max_length=20)),
                ('manager_approval', models.BooleanField(default=False)),
                ('stands_respected', models.BooleanField(editable=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sch.employee')),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.AddField(
            model_name='employee',
            name='shifts_available',
            field=models.ManyToManyField(related_name='available', to='sch.shift'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shifts_trained',
            field=models.ManyToManyField(related_name='trained', to='sch.shift'),
        ),
        migrations.CreateModel(
            name='TemplatedDayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_id', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sch.employee')),
            ],
            options={
                'unique_together': {('employee', 'sd_id')},
            },
        ),
        migrations.CreateModel(
            name='SlotPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iweekday', models.IntegerField()),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('U', 'Urgent')], default='M', max_length=20)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sch.shift')),
            ],
            options={
                'unique_together': {('iweekday', 'shift')},
            },
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('workday', 'shift'), name='Shift Duplicates on day'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('workday', 'employee'), name='Employee Duplicates on day'),
        ),
        migrations.AlterUniqueTogether(
            name='shifttemplate',
            unique_together={('shift', 'ppd_id')},
        ),
        migrations.AlterUniqueTogether(
            name='shiftpreference',
            unique_together={('employee', 'shift')},
        ),
        migrations.AlterUniqueTogether(
            name='schedulingmax',
            unique_together={('employee', 'year', 'pay_period')},
        ),
    ]
