# Generated by Django 4.1.1 on 2022-11-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateddayoff',
            name='ppd_id',
        ),
    ]
