# Generated by Django 4.1.1 on 2022-11-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('sch_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='shift',
            name='cls',
            field=models.CharField(choices=[('CPhT', 'CPhT'), ('RPh', 'RPh')], default='CPhT', max_length=5),
        ),
    ]
