# Generated by Django 4.1.1 on 2022-12-05 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='version',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=37800)),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AlterField(
            model_name='slot',
            name='streak',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
