# Generated by Django 4.1.1 on 2022-12-06 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSortPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sch.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sch.shift')),
            ],
            options={
                'unique_together': {('employee', 'shift')},
            },
        ),
    ]
