# Generated by Django 4.1.1 on 2022-12-01 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0002_remove_templateddayoff_ppd_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='conflicting_slots',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='fillableByN',
        ),
        migrations.AlterField(
            model_name='slot',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='sch.shift'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='workday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='sch.workday'),
        ),
    ]
