# Generated by Django 4.1.1 on 2022-09-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sch", "0002_workday_ppd_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="fte",
            field=models.FloatField(editable=False),
        ),
    ]
