# Generated by Django 4.1.1 on 2022-12-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0002_alter_schedule_slug_alter_schedule_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='slug',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='version',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='shift',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='slot',
            name='streak',
            field=models.SmallIntegerField(default=None, null=True),
        ),
    ]
