# Generated by Django 4.1.1 on 2022-12-08 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0002_shiftsortpreference'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='shift',
            order_with_respect_to='start',
        ),
        migrations.AlterOrderWithRespectTo(
            name='slot',
            order_with_respect_to='shift',
        ),
    ]
