# Generated by Django 4.1.1 on 2022-09-18 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sch", "0003_alter_employee_fte"),
    ]

    operations = [
        migrations.CreateModel(
            name="PtoRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manager_approval", models.BooleanField(default=False)),
                ("stands_respected", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sch.employee"
                    ),
                ),
                (
                    "workday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sch.workday"
                    ),
                ),
            ],
        ),
    ]
