# Generated by Django 4.1.1 on 2022-12-09 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0003_alter_shift_order_with_respect_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['start']},
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['shift__start']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='shift',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='slot',
            order_with_respect_to=None,
        ),
    ]
