# Generated by Django 4.1.1 on 2022-12-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0003_remove_slot_conflicting_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='streak',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fte',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fte_14_day',
            field=models.FloatField(default=80),
        ),
    ]
