# Generated by Django 4.1.1 on 2022-12-05 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0004_slot_streak_alter_employee_fte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
