# Generated by Django 4.1.1 on 2022-12-09 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0004_alter_shift_options_alter_slot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['year', 'number', 'schedule__version']},
        ),
    ]
