# Generated by Django 4.1.1 on 2022-09-18 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sch", "0004_ptorequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="ptorequest",
            name="dateCreated",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ptorequest",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("A", "Approved"), ("D", "Denied")],
                default="P",
                max_length=20,
            ),
        ),
    ]
