# Generated by Django 4.1.1 on 2022-12-09 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0005_alter_week_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={},
        ),
    ]
