# Generated by Django 4.1.1 on 2022-12-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0005_slot_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='created',
        ),
        migrations.AddField(
            model_name='schedule',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2022'),
            preserve_default=False,
        ),
    ]
