# Generated by Django 4.1.1 on 2022-12-05 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0006_remove_slot_created_schedule_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 2, 22, 44, 272753), editable=False),
        ),
    ]
