# Generated by Django 4.1.1 on 2022-09-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sch", "0006_alter_ptorequest_workday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ptorequest",
            name="workday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
