# Generated by Django 4.1.1 on 2022-09-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sch", "0007_alter_ptorequest_workday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ptorequest",
            name="stands_respected",
            field=models.BooleanField(default=True),
        ),
    ]
