# Generated by Django 4.1.1 on 2022-12-17 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0007_employee_time_pref_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftsortpreference',
            options={'ordering': ['score', 'shift']},
        ),
        migrations.AddField(
            model_name='shiftsortpreference',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ptorequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denide', 'Denied')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='shiftpreference',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_prefs', to='sch.employee'),
        ),
        migrations.AlterField(
            model_name='shiftpreference',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_prefs', to='sch.shift'),
        ),
        migrations.AlterField(
            model_name='shiftsortpreference',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_sort_prefs', to='sch.employee'),
        ),
        migrations.AlterField(
            model_name='shiftsortpreference',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_sort_prefs', to='sch.shift'),
        ),
    ]
