# Generated by Django 4.1.1 on 2022-09-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sch", "0008_alter_ptorequest_stands_respected"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="hours",
            field=models.FloatField(default=10, editable=False),
            preserve_default=False,
        ),
    ]
