# Generated by Django 4.1.1 on 2022-12-05 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0008_alter_schedule_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 2, 24, 4, 106413), editable=False),
        ),
    ]
