# Generated by Django 4.1.1 on 2022-12-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0008_alter_shiftsortpreference_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['cls', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='slot',
            name='Shift Duplicates on day',
        ),
        migrations.RemoveConstraint(
            model_name='slot',
            name='Employee Duplicates on day',
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('workday', 'shift', 'schedule'), name='Shift Duplicates on day'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('workday', 'employee', 'schedule'), name='Employee Duplicates on day'),
        ),
    ]
