# Generated by Django 4.1.1 on 2022-09-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sch", "0009_slot_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="hours",
            field=models.FloatField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
