# Generated by Django 4.1.1 on 2022-09-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sch", "0010_shift_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ptorequest",
            name="stands_respected",
            field=models.BooleanField(editable=False),
        ),
    ]
