# Generated by Django 4.1.1 on 2022-12-21 08:17

from django.db import migrations, models
import django.db.models.constraints
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('sch', '0010_alter_schedule_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='slot',
            name='Shift Duplicates on day',
        ),
        migrations.RemoveConstraint(
            model_name='slot',
            name='Employee Duplicates on day',
        ),
        migrations.AddField(
            model_name='slot',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('workday', 'shift', 'schedule'), name='Shift Duplicates on day'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('workday', 'employee', 'schedule'), name='Employee Duplicates on day'),
        ),
    ]
