# Generated by Django 4.1.1 on 2022-12-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0011_remove_slot_shift duplicates on day_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='slot',
            name='Shift Duplicates on day',
        ),
        migrations.RemoveConstraint(
            model_name='slot',
            name='Employee Duplicates on day',
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('workday', 'shift', 'schedule'), name='Shift Duplicates on day'),
        ),
    ]
