# Generated by Django 4.1.1 on 2022-09-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sch", "0011_alter_ptorequest_stands_respected"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlotPriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iweekday", models.IntegerField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("L", "Low"),
                            ("M", "Medium"),
                            ("H", "High"),
                            ("U", "Urgent"),
                        ],
                        default="M",
                        max_length=20,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sch.shift"
                    ),
                ),
            ],
            options={
                "unique_together": {("iweekday", "shift")},
            },
        ),
    ]
