# Generated by Django 4.1.1 on 2022-09-28 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sch", "0012_slotpriority"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("SP", "Strongly Prefer"),
                            ("P", "Prefer"),
                            ("N", "Neutral"),
                            ("D", "Dislike"),
                            ("SD", "Strongly Dislike"),
                        ],
                        default="N",
                        max_length=2,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sch.employee"
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sch.shift"
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "shift")},
            },
        ),
    ]
