# Generated by Django 4.1.1 on 2022-09-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sch", "0013_shiftpreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.FileField(upload_to="photos")),
            ],
        ),
    ]
