# Generated by Django 4.1.1 on 2022-09-29 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sch", "0014_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sch.employee",
            ),
        ),
    ]
