# Generated by Django 4.1.1 on 2022-09-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sch", "0015_alter_slot_employee"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Photo",
        ),
        migrations.AlterUniqueTogether(
            name="slot",
            unique_together={("workday", "shift")},
        ),
        migrations.RemoveField(
            model_name="slot",
            name="end",
        ),
        migrations.RemoveField(
            model_name="slot",
            name="start",
        ),
    ]
