# Generated by Django 4.1.1 on 2023-01-09 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0015_alter_employee_time_pref_alter_shift_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['workday__date', 'shift__start']},
        ),
        migrations.AlterField(
            model_name='slot',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='sch.employee'),
        ),
    ]
