# Generated by Django 4.1.1 on 2023-01-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0016_alter_slot_options_alter_slot_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
