# Generated by Django 4.1.1 on 2023-01-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0017_schedule_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='unfavorable_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.IntegerField(choices=[(0, 'working'), (1, 'finished'), (2, 'discarded')], default=0),
        ),
    ]
