# Generated by Django 4.1.1 on 2022-10-06 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sch", "0017_remove_workday_shifts"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchedulingMax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("pay_period", models.IntegerField(blank=True, null=True)),
                ("max_hours", models.IntegerField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sch.employee"
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "year", "pay_period")},
            },
        ),
    ]
