# Generated by Django 4.1.1 on 2022-10-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sch", "0018_schedulingmax"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftpreference",
            name="score",
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
