# Generated by Django 4.1.1 on 2022-10-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0019_shiftpreference_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='is_turnaround',
            field=models.IntegerField(default=False, editable=False),
            preserve_default=False,
        ),
    ]
