# Generated by Django 4.1.1 on 2023-01-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0019_schedule_tags_week_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
