# Generated by Django 4.1.1 on 2022-10-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0020_slot_is_turnaround'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_iv',
            field=models.BooleanField(default=False),
        ),
    ]
