# Generated by Django 4.1.1 on 2022-10-08 07:32

import computedfields.resolver
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0021_shift_is_iv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iweek', models.IntegerField()),
                ('year', models.IntegerField()),
                ('workdays', models.IntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
    ]
