# Generated by Django 4.1.1 on 2023-01-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0022_employee_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='action_log',
            field=models.TextField(default=''),
        ),
    ]
