# Generated by Django 4.1.1 on 2022-10-13 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0022_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeClass',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='employee_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sch.employeeclass'),
        ),
    ]
