# Generated by Django 4.1.1 on 2022-10-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0022_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='streak',
            field=models.BooleanField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
