# Generated by Django 4.1.1 on 2022-10-13 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0023_employeeclass_shift_employee_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sch.employeeclass'),
        ),
    ]
