# Generated by Django 4.1.1 on 2022-10-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0023_slot_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='streak',
            field=models.IntegerField(editable=False),
        ),
    ]
