# Generated by Django 4.1.1 on 2023-01-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0024_workdayviewpreference_scheduleemusr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdayviewpreference',
            name='view',
            field=models.CharField(choices=[(0, 'wday/wd-detail-2.html'), (1, 'wday/wd-detail.html'), (2, 'wday/wd-detail-old.html')], default=0, max_length=10),
        ),
    ]
