# Generated by Django 4.1.1 on 2022-10-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0025_templateddayoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='ischedule',
            field=models.CharField(default=1, editable=False, max_length=20),
            preserve_default=False,
        ),
    ]
