# Generated by Django 4.1.1 on 2023-01-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0026_schedule_last_update_slot_last_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftpreference',
            options={'ordering': ['shift', '-score']},
        ),
        migrations.AlterField(
            model_name='workdayviewpreference',
            name='view',
            field=models.CharField(choices=[(0, 'wday/wd-detail-2.html'), (1, 'wday/wd-detail.html'), (2, 'wday/wd-detail-old.html'), (3, 'wday/wd-3.html')], default=0, max_length=10),
        ),
    ]
