# Generated by Django 4.1.1 on 2022-10-14 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0024_alter_slot_streak'),
        ('sch', '0026_workday_ischedule'),
    ]

    operations = [
    ]
