# Generated by Django 4.1.1 on 2022-10-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0028_remove_employee_employee_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='is_terminal',
            field=models.BooleanField(default=False, editable=False),
            preserve_default=False,
        ),
    ]
