# Generated by Django 4.1.1 on 2022-10-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0029_slot_is_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='isOverStreakPref',
            field=models.BooleanField(default=False, editable=False),
            preserve_default=False,
        ),
    ]
