# Generated by Django 4.1.1 on 2023-01-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0029_alter_schedule_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='n_empty',
            field=models.IntegerField(default=0),
        ),
    ]
