# Generated by Django 4.1.1 on 2023-01-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0030_schedule_n_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='image_url',
            field=models.CharField(default='/static/img/CuteRobot-01.png', max_length=300),
        ),
    ]
