# Generated by Django 4.1.1 on 2022-10-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0030_slot_isoverstreakpref'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='sd_id',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
