# Generated by Django 4.1.1 on 2023-02-04 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0031_shift_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='time_pref',
            field=models.CharField(choices=[('AM', 'Morning'), ('PM', 'Evening'), ('XN', 'Overnight')], max_length=10),
        ),
        migrations.AlterField(
            model_name='workdayviewpreference',
            name='view',
            field=models.CharField(choices=[(0, 'wday/wd-detail-2.html'), (1, 'wday/wd-detail.html'), (2, 'wday/wd-detail-old.html'), (3, 'wday/wd-3.html'), (4, 'wday/partials/hs_wday.html'), (5, 'wday/wday-4.pug')], default=0, max_length=10),
        ),
        migrations.CreateModel(
            name='RoutineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routine_log', to='sch.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sch.routinelog')),
            ],
        ),
    ]
