# Generated by Django 4.1.1 on 2022-10-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0031_workday_sd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cls',
            field=models.CharField(blank=True, choices=[('CPhT', 'CPhT'), ('RPh', 'RPh')], default='CPhT', max_length=4, null=True),
        ),
    ]
