# Generated by Django 4.1.1 on 2023-02-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0032_alter_employee_time_pref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logevent',
            name='data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
