# Generated by Django 4.1.1 on 2023-02-19 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0033_logevent_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='evening_pref',
        ),
        migrations.AddField(
            model_name='slot',
            name='is_unfavorable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ptorequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pto_requests', to='sch.employee'),
        ),
    ]
