# Generated by Django 4.1.1 on 2022-10-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0033_shift_cls'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateddayoff',
            name='sd_id',
            field=models.IntegerField(null=True),
        ),
    ]
