# Generated by Django 4.1.1 on 2023-02-21 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0034_remove_employee_evening_pref_slot_is_unfavorable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftsortpreference',
            name='scaled',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shiftpreference',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_prefs', to='sch.shift'),
        ),
        migrations.AlterField(
            model_name='shiftsortpreference',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sort_prefs', to='sch.shift'),
        ),
    ]
