# Generated by Django 4.1.1 on 2023-02-23 07:32

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0035_shiftsortpreference_scaled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slug',
            field=models.CharField(default=django.db.models.expressions.CombinedExpression(models.F('workday'), '+', models.F('shift')), max_length=100, null=True),
        ),
    ]
