# Generated by Django 4.1.1 on 2023-02-26 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0036_slot_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='hours',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='shiftpreference',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefs', to='sch.shift'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
