# Generated by Django 4.1.1 on 2022-10-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0036_slot_is_preturnaround'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='evening_pref',
            field=models.BooleanField(default=False),
        ),
    ]
