# Generated by Django 4.1.1 on 2022-10-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0037_employee_evening_pref'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('workday', 'shift'), name='Shift Duplicates on day'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('workday', 'employee'), name='Employee Duplicates on day'),
        ),
    ]
