# Generated by Django 4.1.1 on 2022-10-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0037_employee_evening_pref'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workday',
            name='periodId',
            field=models.IntegerField(default='P', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workday',
            name='scheduleId',
            field=models.IntegerField(default='S', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workday',
            name='weekId',
            field=models.IntegerField(default='W', editable=False),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('workday', 'shift'), name='Shift Duplicates on day'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('workday', 'employee'), name='Employee Duplicates on day'),
        ),
    ]
