# Generated by Django 4.1.1 on 2022-10-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0038_alter_slot_unique_together_workday_periodid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='periodId',
            field=models.CharField(editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='workday',
            name='scheduleId',
            field=models.CharField(editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='workday',
            name='weekId',
            field=models.CharField(editable=False, max_length=8),
        ),
    ]
