# Generated by Django 4.1.1 on 2022-10-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0038_alter_slot_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='trade_one_offs',
            field=models.BooleanField(default=True),
        ),
    ]
