# Generated by Django 4.1.1 on 2023-02-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sch", "0038_schedule_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="period",
            name="hours",
            field=models.JSONField(default={}),
        ),
    ]
