# Generated by Django 4.1.1 on 2023-02-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sch", "0039_period_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="weekly_hours",
            field=models.JSONField(default={}),
        ),
    ]
