# Generated by Django 4.1.1 on 2022-10-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0039_employee_trade_one_offs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='workdays',
        ),
        migrations.AddField(
            model_name='workday',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='sch.week'),
        ),
    ]
