# Generated by Django 4.1.1 on 2022-10-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0039_alter_workday_periodid_alter_workday_scheduleid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='periodId',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='scheduleId',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='weekId',
        ),
    ]
