# Generated by Django 4.1.1 on 2023-03-01 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sch", "0040_schedule_weekly_hours"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logevent",
            options={"ordering": ["-id"]},
        ),
    ]
