# Generated by Django 4.1.1 on 2022-10-27 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0041_alter_workday_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='sch.week'),
        ),
    ]
