# Generated by Django 4.1.1 on 2023-03-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sch", "0041_alter_logevent_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="workday",
            name="pto_requests",
            field=models.ManyToManyField(
                blank=True, related_name="workdays", to="sch.ptorequest"
            ),
        ),
    ]
