# Generated by Django 4.1.1 on 2022-10-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0042_alter_workday_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='iweek',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='workday',
            name='iweekday',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
