# Generated by Django 4.1.1 on 2023-03-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sch", "0043_logevent_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ptorequest",
            name="schedules",
            field=models.ManyToManyField(
                related_name="pto_requests", to="sch.schedule"
            ),
        ),
    ]
