# Generated by Django 4.1.1 on 2022-10-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0043_alter_workday_iweek_alter_workday_iweekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='ischedule',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
    ]
