# Generated by Django 4.1.1 on 2023-03-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sch", "0044_ptorequest_schedules"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shift",
            options={"ordering": ["start", "name"]},
        ),
        migrations.AlterModelOptions(
            name="slot",
            options={"ordering": ["workday__date", "shift__start", "employee__name"]},
        ),
        migrations.AddField(
            model_name="scheduleemusr",
            name="n_unfav",
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scheduleemusr",
            name="n_var",
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scheduleemusr",
            name="std_dev",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schedule",
            name="weekly_hours",
            field=models.JSONField(default={"all": 0}),
        ),
    ]
