# Generated by Django 4.1.1 on 2022-10-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0044_alter_workday_ischedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='group',
            field=models.CharField(choices=[('AM', 'AM'), ('MD', 'MD'), ('PM', 'PM'), ('XN', 'XN')], max_length=10, null=True),
        ),
    ]
