# Generated by Django 4.1.1 on 2022-10-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0045_shift_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='empl_sentiment',
            field=models.SmallIntegerField(default=50),
        ),
    ]
