# Generated by Django 4.1.1 on 2023-03-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sch", "0045_alter_shift_options_alter_slot_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slot",
            options={"ordering": ["workday__date", "shift__start", "shift__name"]},
        ),
        migrations.AddField(
            model_name="shift",
            name="coverage_for",
            field=models.ManyToManyField(
                blank=True, related_name="covers", to="sch.shift"
            ),
        ),
    ]
