# Generated by Django 4.1.1 on 2023-04-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sch", "0046_alter_slot_options_shift_coverage_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="std_wk_max",
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name="schedule",
            name="prn_maxes",
            field=models.ManyToManyField(
                related_name="schedules", to="sch.schedulingmax"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="fte",
            field=models.FloatField(default=-1),
        ),
    ]
