# Generated by Django 4.1.1 on 2023-04-03 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sch", "0047_employee_std_wk_max_schedule_prn_maxes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedulingmax",
            old_name="pay_period",
            new_name="number",
        ),
        migrations.AlterUniqueTogether(
            name="schedulingmax",
            unique_together={("employee", "year", "number")},
        ),
    ]
