# Generated by Django 4.1.1 on 2022-11-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0048_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
