# Generated by Django 4.1.1 on 2023-04-21 02:40

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("sch", "0048_remove_schedule_prn_maxes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="period",
            name="hours",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="shift",
            name="occur_days",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    (0, "Sun"),
                    (1, "Mon"),
                    (2, "Tue"),
                    (3, "Wed"),
                    (4, "Thu"),
                    (5, "Fri"),
                    (6, "Sat"),
                ],
                default=[0, 1, 2, 3, 4, 5, 6],
                max_length=14,
            ),
        ),
        migrations.CreateModel(
            name="Turnaround",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turnarounds",
                        to="sch.employee",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turnarounds",
                        to="sch.schedule",
                    ),
                ),
                (
                    "slots",
                    models.ManyToManyField(related_name="turnarounds", to="sch.slot"),
                ),
            ],
        ),
    ]
