# Generated by Django 4.1.1 on 2022-11-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0049_week_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
