# Generated by Django 4.1.1 on 2022-11-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0050_week_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='iweek',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
