# Generated by Django 4.1.1 on 2022-11-24 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0051_alter_week_iweek_alter_week_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sch.schedule'),
        ),
    ]
