# Generated by Django 4.1.1 on 2023-05-05 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sch", "0051_shift_phase_alter_period_hours_alter_week_hours"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="pto_hrs",
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sch.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shift",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sch.department",
            ),
        ),
    ]
