# Generated by Django 4.1.1 on 2023-05-05 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sch", "0052_organization_employee_pto_hrs_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sch.department",
            ),
        ),
    ]
