# Generated by Django 4.1.1 on 2022-11-24 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0052_week_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=datetime.date(2018, 4, 11)),
        ),
    ]
