# Generated by Django 4.1.1 on 2022-11-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0053_employee_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='n_trained',
            field=models.IntegerField(default=1),
        ),
    ]
