# Generated by Django 4.1.1 on 2023-05-06 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sch", "0053_employee_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="department",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sch.department",
            ),
        ),
    ]
