# Generated by Django 4.1.1 on 2022-11-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0054_employee_n_trained'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptorequest',
            name='sd_id',
            field=models.IntegerField(default=-1),
        ),
    ]
