# Generated by Django 4.1.1 on 2022-11-26 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0055_ptorequest_sd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.IntegerField(choices=[(0, 'w'), (1, 'o'), (2, 'r'), (3, 'k'), (4, 'i'), (5, 'n'), (6, 'g'), (7, ','), (8, 'f'), (9, 'i'), (10, 'n'), (11, 'i'), (12, 's'), (13, 'h'), (14, 'e'), (15, 'd'), (16, ','), (17, 'd'), (18, 'i'), (19, 's'), (20, 'c'), (21, 'a'), (22, 'r'), (23, 'd'), (24, 'e'), (25, 'd')], default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='version',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sch.schedule')),
            ],
        ),
    ]
