# Generated by Django 4.1.1 on 2023-05-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sch", "0055_alter_department_org_alter_period_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="initials",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("initials", "department")},
        ),
    ]
