# Generated by Django 4.1.1 on 2022-11-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0056_schedule_status_schedule_version_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='sch.period'),
        ),
        migrations.AddField(
            model_name='workday',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='sch.schedule'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='empl_sentiment',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sch.employee'),
        ),
    ]
