# Generated by Django 4.1.1 on 2022-11-26 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0057_workday_period_workday_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='schedule',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sch.schedule'),
            preserve_default=False,
        ),
    ]
