# Generated by Django 4.1.1 on 2022-11-26 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0058_alter_week_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sch.period'),
        ),
        migrations.AddField(
            model_name='slot',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sch.schedule'),
        ),
        migrations.AddField(
            model_name='slot',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sch.week'),
        ),
        migrations.AddField(
            model_name='week',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sch.period'),
        ),
        migrations.AlterField(
            model_name='week',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sch.schedule'),
        ),
    ]
