# Generated by Django 4.1.1 on 2022-11-26 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0059_slot_period_slot_schedule_slot_week_week_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='conflicting_slots',
            field=models.ManyToManyField(default=None, null=True, to='sch.slot'),
        ),
        migrations.AlterField(
            model_name='period',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='sch.schedule'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='sch.employee'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='sch.period'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='sch.schedule'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='sch.shift'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='sch.week'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='workday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='sch.workday'),
        ),
        migrations.AlterField(
            model_name='week',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='sch.period'),
        ),
        migrations.AlterField(
            model_name='week',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='sch.schedule'),
        ),
    ]
