# Generated by Django 4.2.1 on 2023-05-12 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0060_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='initial_start_date',
            field=models.DateField(default=datetime.date(2022, 12, 25)),
        ),
        migrations.AddField(
            model_name='department',
            name='schedule_week_length',
            field=models.IntegerField(choices=[(2, 2), (4, 4), (6, 6), (8, 8), (10, 10)], default=6),
        ),
    ]
