# Generated by Django 4.1.1 on 2022-11-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0060_slot_conflicting_slots_alter_period_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
