# Generated by Django 4.1.1 on 2022-11-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0062_slot_fillablebyn'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='slug',
            field=models.SlugField(default='blah-blah'),
            preserve_default=False,
        ),
    ]
