# Generated by Django 4.1.1 on 2023-05-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sch", "0062_customuser_delete_workdayviewpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(default="joshy", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
