# Generated by Django 4.1.1 on 2023-05-12 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sch", "0063_customuser_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmployeeClass",
        ),
    ]
