# Generated by Django 4.1.1 on 2023-04-19 12:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField()),
                ("schedule_week_count", models.IntegerField(default=6)),
                ("schedule_period_count", models.IntegerField(default=3)),
                (
                    "schedule_start_date",
                    models.DateField(default=datetime.date(2022, 12, 25)),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("year", models.SmallIntegerField()),
                ("number", models.SmallIntegerField()),
                ("slug", models.SlugField()),
                ("published", models.BooleanField(default=False)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="main.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1)),
                ("percent", models.SmallIntegerField()),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="main.schedule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField()),
                (
                    "weekdays",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("S", "Sunday"),
                            ("M", "Monday"),
                            ("T", "Tuesday"),
                            ("W", "Wednesday"),
                            ("R", "Thursday"),
                            ("F", "Friday"),
                            ("A", "Saturday"),
                        ],
                        default="MTWRF",
                        max_length=100,
                    ),
                ),
                ("hours", models.SmallIntegerField()),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="main.department",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="schedule",
            name="published_version",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_version",
                to="main.version",
            ),
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("initials", models.CharField(max_length=4, unique=True)),
                ("slug", models.SlugField()),
                ("hire_date", models.DateField(default=datetime.date(2020, 5, 1))),
                ("active", models.BooleanField()),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="main.department",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="department",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="main.organization",
            ),
        ),
    ]
