# Generated by Django 4.1.1 on 2023-04-30 19:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutoSlugFieldModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=300, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField()),
                (
                    "schedule_week_count",
                    models.IntegerField(
                        choices=[(2, 2), (4, 4), (6, 6), (8, 8)], default=6
                    ),
                ),
                (
                    "schedule_start_date_init",
                    models.DateField(default=datetime.date(2022, 12, 25)),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("initials", models.CharField(max_length=4)),
                ("fte", models.FloatField(default=1.0)),
                ("hire_date", models.DateField(default=datetime.date(2020, 5, 1))),
                ("active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="main.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("year", models.SmallIntegerField()),
                ("number", models.SmallIntegerField()),
                ("slug", models.SlugField()),
                ("published", models.BooleanField(default=False)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="main.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                (
                    "weekdays",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("S", "Sunday"),
                            ("M", "Monday"),
                            ("T", "Tuesday"),
                            ("W", "Wednesday"),
                            ("R", "Thursday"),
                            ("F", "Friday"),
                            ("A", "Saturday"),
                        ],
                        default=["S", "M", "T", "W", "R", "F", "A"],
                        max_length=100,
                    ),
                ),
                ("hours", models.SmallIntegerField(default=10)),
                (
                    "phase",
                    models.IntegerField(
                        choices=[(0, "AM"), (1, "MD"), (2, "PM"), (3, "EV"), (4, "XN")],
                        default=0,
                    ),
                ),
                ("on_holidays", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="main.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="main.employee",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="main.shift",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1)),
                ("percent", models.SmallIntegerField()),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="main.schedule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PtoSlot",
            fields=[
                (
                    "slot_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.slot",
                    ),
                ),
            ],
            bases=("main.slot",),
        ),
        migrations.CreateModel(
            name="Workday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workdays",
                        to="main.version",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="slot",
            name="workday",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="main.workday",
            ),
        ),
        migrations.CreateModel(
            name="PtoRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("hours", models.SmallIntegerField()),
                ("approved", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pto_requests",
                        to="main.employee",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="shifts_available",
            field=models.ManyToManyField(
                blank=True,
                help_text="All shifts this employee is available to work and is in the active rotation for. \n                    Trained shifts not also marked as available will never be scheduled by the AI, \n                    but will allow for manual assignments.",
                related_name="employees_available",
                to="main.shift",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="shifts_trained",
            field=models.ManyToManyField(
                blank=True,
                help_text="All shifts this employee is trained to work.",
                related_name="employees_trained",
                to="main.shift",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="main.organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.UniqueConstraint(
                fields=("schedule", "name"), name="version"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.UniqueConstraint(
                fields=("year", "number", "department"), name="schedule"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("name", "organization")},
        ),
    ]
