# Generated by Django 4.1.1 on 2023-05-01 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_version_created_by_alter_employee_shifts_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="version",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("DFT", "Draft"), ("PUB", "Published"), ("ARC", "Archived")],
                default="DFT",
                max_length=3,
                null=True,
            ),
        ),
    ]
