# Generated by Django 4.1.1 on 2023-05-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_version_created_at_version_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="std_weekly_hours",
            field=models.SmallIntegerField(default=40),
        ),
    ]
