# Generated by Django 4.1.1 on 2023-05-01 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_employee_std_weekly_hours"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayOffMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "days_off",
                    models.CharField(
                        default="",
                        help_text="Comma-separated list of days off, e.g. 'M,T,W'",
                        max_length=100,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_off_maps",
                        to="main.employee",
                    ),
                ),
            ],
        ),
    ]
