# Generated by Django 4.1.1 on 2023-05-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_dayoffmap"),
    ]

    operations = [
        migrations.AddField(
            model_name="workday",
            name="pdid",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workday",
            name="sdid",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workday",
            name="wkid",
            field=models.SmallIntegerField(default=0),
        ),
    ]
