# Generated by Django 4.1.1 on 2023-05-01 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_workday_pdid_workday_sdid_workday_wkid"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="employees",
            field=models.ManyToManyField(
                blank=True, related_name="schedules", to="main.employee"
            ),
        ),
        migrations.CreateModel(
            name="ShiftPref",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.SmallIntegerField(default=0)),
                (
                    "qual",
                    models.SmallIntegerField(
                        choices=[(0, "SD"), (1, "D"), (2, "N"), (3, "P"), (4, "SP")],
                        default=0,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_prefs",
                        to="main.employee",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_prefs",
                        to="main.shift",
                    ),
                ),
            ],
        ),
    ]
