# Generated by Django 4.1.1 on 2023-05-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_schedule_employees_shiftpref"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ptorequest",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="ptorequest",
            name="date",
        ),
        migrations.RemoveField(
            model_name="ptorequest",
            name="hours",
        ),
        migrations.AddField(
            model_name="ptorequest",
            name="sdid",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ScheduleBasePtoCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pto_calendars",
                        to="main.employee",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pto_calendars",
                        to="main.schedule",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ptorequest",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pto_requests",
                to="main.schedulebaseptocalendar",
            ),
        ),
    ]
