# Generated by Django 4.1.1 on 2023-05-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_remove_ptorequest_approved_remove_ptorequest_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="admin",
            field=models.BooleanField(default=False),
        ),
    ]
