# Generated by Django 4.1.1 on 2022-10-18 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diluent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solute', models.CharField(max_length=100)),
                ('concentration', models.CharField(max_length=20)),
                ('volume', models.FloatField(choices=[('mL', 'mL'), ('L', 'L')])),
            ],
        ),
        migrations.AlterField(
            model_name='drug',
            name='unit_size',
            field=models.CharField(choices=[('mg', 'mg'), ('µg', 'µg'), ('gm', 'gm')], max_length=10),
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diluent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pds.diluent')),
                ('drugs', models.ManyToManyField(related_name='compounds', to='pds.drug')),
            ],
        ),
    ]
