# Generated by Django 4.1.1 on 2022-11-30 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
