# Generated by Django 4.1.1 on 2023-01-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RxUser',
        ),
    ]
