name: Django CI

on:
  push:
    branches: [ "beforeSlow" ]
  pull_request:
    branches: [ "beforeSlow" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Cache
      uses: actions/cache@v2.1.8
      with:
        # A list of files, directories, and wildcard patterns to cache and restore path: 
        # An explicit key for restoring and saving the cache key: 
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key restore-keys: # optional
        # The chunk size used to split up large files during upload, in bytes upload-chunk-size: # optional
